name: Wiki PDF

on:
  gollum

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}.wiki
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/Tectonic/
          key: ${{ runner.os }}-${{ env.cache-name }}-tectonic
      - name: Download pandoc+tectonic
        run: |
          wget -qO- https://github.com/tectonic-typesetting/tectonic/releases/download/tectonic%400.3.3/tectonic-0.3.3-x86_64-unknown-linux-gnu.tar.gz | tar xzvf - tectonic
          wget -qO- https://github.com/jgm/pandoc/releases/download/2.11.3.1/pandoc-2.11.3.1-linux-amd64.tar.gz | tar --strip-components=2 -xzvf - pandoc-2.11.3.1/bin/pandoc
          sudo mv -f pandoc tectonic /usr/local/bin
      - name: Build PDF
        run: |
          pandoc Home.md -s --pdf-engine tectonic -o userguide.pdf
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v2
        with:
          name: userguide
          path: userguide.pdf
